name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Build extension
      run: npm run build
    
    - name: Get version
      id: get_version
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        echo "VERSION_NUMBER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          Chrome拡張機能 X to Bird ${{ steps.get_version.outputs.VERSION }}
          
          ## インストール方法
          1. 下記のZIPファイルをダウンロード
          2. Chrome拡張機能ページ（chrome://extensions/）を開く
          3. デベロッパーモードを有効化
          4. 「パッケージ化されていない拡張機能を読み込む」でZIPを解凍したフォルダを選択
          
          ## 変更履歴
          [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) を参照
        draft: false
        prerelease: false
    
        files: ./dist/x-to-bird-v${{ steps.get_version.outputs.VERSION_NUMBER }}.zip